<?php
    $section = 'parser-plugins';
    $subpage = 'ref-plugin-parse_locjson';
    $title = 'LocJSON Parser Plugin';
    include($_SERVER['DOCUMENT_ROOT'] . '/../inc/documentation-header.php');

    $available_since = '1.5';
    include($_SERVER['DOCUMENT_ROOT'] . '/../inc/version-selector.php');
?>

<h1><?php echo htmlspecialchars($title) ?></h1>

<p>Plugin source location: <code>&lt;serge_root&gt;/lib/Serge/Engine/Plugin/parse_locjson.pm</code></p>

<p>This plugin is used to parse monolingual <a href="https://github.com/iafan/LocJSON">LocJSON files</a>.</p>

<p>This is a validating parser. In case LocJSON format validation fails, the plugin can send an error report to specified recipients. If no email settings are provided, it will simply report the error in the console output.</p>

<h2>Code Examples</h2>

<figure>
    <figcaption>products.locjson</figcaption>
    <code class="block">{
    "properties": {
        "comments": ["This file was generated by AwesomeTool"],
    },
    "units": [
        {
            "key": "<span class="context">welcomeMessage</span>",
            "properties": {
                "comments": [
                    "<span class="hint">{USER} is the first name of a signed in user</span>"
                ]
            },
            "source": [
                "<span class="string">Hello, {USER}!</span>"
            ]
        },
        {
            "key": "<span class="context">signInButtonCaption</span>",
            "properties": {
                "comments": [
                    "<span class="hint">https://example.com/preview/sign-in.png</span>"
                ]
            },
            "source": [
                "<span class="string">Sign In</span>"
            ]
        },
        {
            "key": "<span class="context">signInFooterText</span>",
            "properties": {
                "comments": [
                    "<span class="hint">This text is displayed below the sign in form.</span>",
                    "<span class="hint">https://example.com/preview/sign-in.png</span>"
                ]
            },
            "source": [
                "<span class="string">Please read our &lt;a </span>",
                "<span class="string">href=\"https://example.com/legal/pp\"&gt;Privacy </span>",
                "<span class="string">Policy&lt;/a&gt; and &lt;a </span>",
                "<span class="string">href=\"https://example.com/legal/tos\"&gt;Terms of </span>",
                "<span class="string">Service&lt;/a&gt;</span>"
            ]
        }
    ]
}
</code>
</figure>

<p>Please see the example configuration file below to learn why only <code>title</code> and certain <code>description</code> nodes are extracted here for translation.</p>

<h2>Usage</h2>

<figure>
    <figcaption>example-project.serge</figcaption>
    <script language="text/x-config-neat">
jobs
{
    :sample-job
    {
        parser
        {
            plugin                   parse_locjson

            data
            {
                /*
                (BOOLEAN) [OPTIONAL] Whether to remove
                all "properties" sections from the generated
                files to reduce file size.
                Default: NO
                */
                remove_properties    NO

                /*
                (STRING) [OPTIONAL] Email to send
                error reports on behalf of
                */
                email_from           l10n-robot@acme.org

                /*
                (ARRAY) [OPTIONAL] One or more email
                addresses to send error reports to
                */
                email_to             engineer@acme.org
                                     project-manager@acme.org

                /*
                (STRING) [OPTIONAL] Email subject
                */
                email_subject        Errors found in LocJSON file
            }
        }

        # other job parameters
        # ...
    }
}
</script>
</figure>

<?php include($_SERVER['DOCUMENT_ROOT'] . '/../inc/documentation-footer.php') ?>
