<?php
    $section = 'serializer-plugins';
    $subpage = 'ref-plugin-serialize_csv';
    $title = '.CSV Serializer Plugin';
    include($_SERVER['DOCUMENT_ROOT'] . '/../inc/documentation-header.php');

    $available_since = '1.2';
    include($_SERVER['DOCUMENT_ROOT'] . '/../inc/version-selector.php');
?>

<h1><?php echo htmlspecialchars($title) ?></h1>

<p>Plugin source location: <code>&lt;serge_root&gt;/lib/Serge/Engine/Plugin/serialize_csv.pm</code></p>

<p>This plugin serializes/parses translation files in .CSV format. The generated CSV files are UTF-8-encoded and have the following columns:</p>

<ol>
    <li><code>ID</code> &mdash; string ID</li>
    <li><code>Context</code> &mdash; string context</li>
    <li><code>Hint</code> &mdash; comment provided by developers or generated by Serge</li>
    <li><code>Source</code> &mdash; source string</li>
    <li><code>Translation</code> &mdash; current translation (or empty if no translation is provided yet)</li>
    <li><code>Needs Work</code> &mdash; flag that indicates that the translation is not final; any value different from empty value or <code>0</code> is considered a 'true' one.</li>
    <li><code>Translator's Comment</code> &mdash; optional comment that translator may set</li>
</ol>

<p>Translators are supposed to alter only <code>Translation</code>, <code>Needs Work</code> and <code>Translator's Comment</code> columns. They can provide new values, edit or remove existing ones. Other columns are considered read-only. Changing <code>ID</code>, <code>Context</code> or <code>Source</code> filed values will render the line invalid and any changes in such row, including changes done to other fields, will be reverted on subsequent CSV file update. Changes to <code>Hint</code> value will also be reverted.</p>

<h2>Example</h2>

<figure>
    <figcaption>source-file.ext.csv</figcaption>
    <code class="block">ID,Context,Hint,Source,Translation,Needs Work,Translator's Comment
b27b28fa4633c77743f378907ae13b73,,Email subject,ACME account activation,,,
3fd521e005eae6802f087c09d18a058d,,,The ACME team,,,
</code>
</figure>

<h2>Usage</h2>

<figure>
    <figcaption>example-project.serge</figcaption>
    <script language="text/x-config-neat">
jobs
{
    :sample-job
    {
        serializer
        {
            plugin               serialize_csv
        }

        # other job parameters
        # ...
    }
}
</script>
</figure>

<?php include($_SERVER['DOCUMENT_ROOT'] . '/../inc/documentation-footer.php') ?>